Skip SonarQube scan for PR from fork and allow compare_db workflow from fork (#327)
* check if PR is from a fork and skip SonarQube scan if so -- fail job so it is clear that the scan was not run

* specify repository of source branch in PR to allow PR from forked repository

* change condition to run coverage report generation to only run if the step to check for a fork PR is skipped, meaning the tests should run

* fixed syntax error

diff --git a/.github/workflows/sonarqube.yaml b/.github/workflows/sonarqube.yaml
--- a/.github/workflows/sonarqube.yaml
+++ b/.github/workflows/sonarqube.yaml
@@ -43,6 +43,10 @@ jobs:
 
     steps:
 
+    - name: Check if PR is from a fork
+      id: check_fork
+      if: ${{ github.event.pull_request.head.repo.full_name != 'dtcenter/METdataio' }}
+      run: echo "SonarQube scan cannot be run from a fork"; exit 1
     - uses: actions/checkout@v4
       with:
         # Disable shallow clones for better analysis
@@ -76,11 +80,11 @@ jobs:
 
     - name: Output coverage report
       run: coverage report -m
-      if: always()
+      if: ${{ always() && steps.check_fork.conclusion == 'skipped' }}
 
     - name: Generate XML coverage report
       run: coverage xml
-      if: always()
+      if: ${{ always() && steps.check_fork.conclusion == 'skipped' }}
 
     - name: Get branch name
       id: get_branch_name
